name: "Whitelist GitHub IP + cleanup"

on:
  workflow_call:
    inputs:
      firewall_name:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  whitelist:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.get_ip.outputs.ip }}
    steps:
      - name: Get public IP of runner
        id: get_ip
        run: echo "::set-output name=ip::$(curl -s https://ifconfig.me)"

      - name: Whitelist GitHub runner IP
        uses: adnanjaw/ip-whitelist-on-hetznerfw@v2
        with:
          hetzner_api_key: ${{ secrets.HETZNER_FIREWALL_API_TOKEN }}
          ip_address: ${{ steps.get_ip.outputs.ip }}
          firewall_name: ${{ inputs.firewall_name }}
          port: ${{ inputs.port }}
          protocol: tcp
          direction: in
          description: "github-actions-${{ github.run_id }}"
          cleanup: false  # on nettoie manuellement après deploy
